DemoCoreApp/DemoCoreApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoCoreApp.Models;
using DemoCoreApp.DBAccess;
using Microsoft.AspNetCore.Http;
using DemoCoreApp.ViewModels;
using DemoCoreApp.Services;

namespace DemoCoreApp.Controllers
{
    [Route("[controller]")]
    public class HomeController : Controller
    {
        private readonly IOwnerVehicleRepo _ownerVehicleRepo;
        private readonly IAppService _appService;

        public HomeController(IOwnerVehicleRepo owerVehicleRepo, IAppService appService)
        {
            _ownerVehicleRepo = owerVehicleRepo;
            _appService = appService;

        }
        [Route("")]
        [Route("~/")]
        
        public ViewResult Index()
        {
            var id = HttpContext.Session.GetInt32("ownerId");
            if ( HttpContext.Session.GetInt32("ownerId") != null)
            {
                return View();
            }
            else
            {
                return View("../Login/Login");
            }
        }

        //[HttpGet]
        //[Route("Login")]
        //public ViewResult Login()
        //{
        //    return View("../Home/Login");
        //}

        [HttpGet]
        [Route("About")]
        public IActionResult About()
        {
            var listOfVehicles = _appService.GetAllVehicles();

            return View(listOfVehicles);
        }

        [HttpGet]
        [Route("Contact")]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }


        [HttpGet]
        [Route("CreateAccount")]
        public ViewResult CreateAccount()
        {
            return View("../Owner/AddEditOwner");
        }

        [HttpPost]
        [Route("AddUpdateAccount")]
        public RedirectToActionResult AddUpdateAccount(Owner owner)
        {
           _appService.UpSertOwenrInfo(owner);
            //ViewBag.Success = isSuccessful; 
           return RedirectToAction("");
        }

        //[HttpPost]
        //[Route("ValidateOwner")]
        //public RedirectToActionResult ValidateOwner(Owner owner)
        //{
        //    if (!string.IsNullOrWhiteSpace(owner.Email) && !string.IsNullOrWhiteSpace(owner.ApartmentNumber))
        //    {
        //        owner.Id = _appService.ValidateOwnerInfo(owner.Email, owner.ApartmentNumber);
        //    }

        //   HttpContext.Session.SetInt32("ownerId", owner.Id.Value);
        //    return RedirectToAction("Register","Vehicle");
        //}

        [HttpPost]
        [Route("FindVehicle")]
        public ViewResult SearchForVehicle(Vehicle vehicle)
        {
            var viewModel = new OwnerVehicleViewModel();
            if (!string.IsNullOrWhiteSpace(vehicle.RegistrationNumber))
            {
               viewModel = _appService.GetOwnerVehicleInfo(vehicle.RegistrationNumber);
            }
            return View("../Vehicle/VehicleInfo",viewModel);
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

DemoCoreApp/DemoCoreApp/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DemoCoreApp.Models;
using DemoCoreApp.Services;
using DemoCoreApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DemoCoreApp.Controllers
{
    [Route("[controller]")]
    public class VehicleController : Controller
    {
        
        private readonly IOwnerVehicleRepo _ownerVehicleRepo;
        private readonly IAppService _appService;

        public VehicleController(IOwnerVehicleRepo vehicleRepo, IAppService appService)
        {
            _ownerVehicleRepo = vehicleRepo;
            _appService = appService;
        }

        [HttpGet]
        [Authorize]
        [Route("Register")]
        public ViewResult Register()
        {
            return View("../Vehicle/RegisterVehicle");
        }

        [HttpGet]
        [Route("Edit/{Id?}")]
        public ViewResult EditVehicelInfo(int Id)
        {
            var vehicle = _appService.GetVehicleInfo(Id);
            var viewModel = new VehicleViewModel()
            {
                VehicleOwnerId = vehicle.VehicleOwnerId,
                VehicleId = vehicle.VehicleId,
                Make = vehicle.Make,
                Model = vehicle.Model,
                Color = vehicle.Color,
                RegistrationNumber = vehicle.RegistrationNumber
            };
            return View("../Vehicle/EditVehicle", viewModel);
        }

        [HttpPost]
        [Route("Edit")]
        public ViewResult Edit(VehicleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicle = new Vehicle()
                {
                    VehicleOwnerId = viewModel.VehicleOwnerId,
                    VehicleId = viewModel.VehicleId,
                    Make = viewModel.Make,
                    Model = viewModel.Model,
                    Color = viewModel.Color,
                    RegistrationNumber = viewModel.RegistrationNumber
                };
                _appService.UpsertVehicleInfo(vehicle, vehicle.VehicleOwnerId.Value);
                return View("../Vehicle/VehicleInfo", vehicle);
            }
            else
            {
                return View("../Vehicle/EditVehicle", viewModel);
            }
        }

        [HttpPost]
        [Authorize]
        [Route("RegisterVehicle")]
        public IActionResult RegisterVehicle(VehicleViewModel viewModel)
        {
            if (ModelState.IsValid) {
                var vehicle = new Vehicle()
                {
                    VehicleId = viewModel.VehicleId,
                    Make = viewModel.Make,
                    Model = viewModel.Model,
                    Color = viewModel.Color,
                    RegistrationNumber = viewModel.RegistrationNumber
                };
                var ownerId = HttpContext.Session.GetInt32("ownerId");
                _appService.UpsertVehicleInfo(vehicle, ownerId.Value);
                return RedirectToAction("", "Home");
            }
            else
            {
                return View("../Vehicle/RegisterVehicle");
            }
        }
        //public string VehicleInfo()
        //{
        //  return  _vehicleRepo.GetVehicle(1).RegistrationNumber;
        //}

        //public ViewResult VehicleInfo()
        //{
        //    Vehicle vehicleModel =  _vehicleRepo.GetVehicle(1);
        //    return View("../Home/About", vehicleModel); // relative path no file extention if View/Home/About.cshtml
        //}
        //[Route("VehicleInfo/{vid?}")]

        //public ViewResult VehicleInfo(int vid)
        //{
        //    OwnerVehicleViewModel viewModel = new OwnerVehicleViewModel()
        //    {
        //        Vehicle = _vehicleRepo.GetVehicle(vid)
        //        //Owner = _ownerRepo.GetOwner(oid)
        //    };
        //    //Vehicle vehicleModel = _vehicleRepo.GetVehicle(1);
        //    //Owner owenerModel = _ownerRepo.GetOwner(1);

        //    //ViewBag.RegistrationNumber = vehicleModel.RegistrationNumber;
        //    //ViewData["Vehicle"] = vehicleModel; // passing losely type Viewdata dynamically resolved at on run time.
        //    return View(viewModel);
        //}

        [Route("GetAll")]
        public ViewResult GetAllVehicles()
        {
            List<Vehicle> vehicles = _appService.GetAllVehicles();
            return View("../Home/About", vehicles);
        }
    }
}

DemoCoreApp/DemoCoreApp/Views/Home/About.cshtml
@model IEnumerable<Vehicle>

@{
    ViewData["Title"] = "About";
}
@*<h3>@ViewData["Message"]</h3>*@

@*<p>Use this area to provide additional information.</p>*@

<h2>All Vehicles</h2>
    <table border="1">
       <tr>
           <td>
               ID
           </td>
           <td>
               Model
           </td>
           <td>
               Make
           </td>
           <td>
               Action
           </td>
       </tr>
            @foreach (var v in Model)
            {
        <tr>
            <td>
                @v.VehicleId

            </td>


            <td>
                @v.Model
            </td>


            <td>
                @v.Make
            </td>
            <td>
                <a href="/Vehicle/VehicleInfo/@v.VehicleId">View</a>
                <a href="@Url.Action("VehicleInfo","Vehicle",new {vid= v.VehicleId })" class="btn-default">Show</a>
                <a asp-controller="vehicle" asp-action="VehicleInfo" asp-route-vid="@v.VehicleId" class="btn btn-primary"> Details</a>
            </td>
        </tr>
            }

    </table>

@*<a href="/VehicleInfo/@Model.Vehicle.VehicleId">View</a>*@

DemoCoreApp/DemoCoreApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DemoCoreApp/DemoCoreApp/Views/Home/Index.cshtml
@model DemoCoreApp.ViewModels.OwnerVehicleViewModel
@{
    ViewData["Title"] = "Home Page";
    var isSuccessful = ViewBag.Isvalid;
}
@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Learn how to build ASP.NET apps that can run anywhere.
                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        There are powerful new features in Visual Studio for building modern web apps.
                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>*@
@*@if (isSuccessful != null)
{
    if (isSuccessful)
    {
        <div class="alert alert-success">
            <strong>Success!</strong> Request completed successfully.
        </div>
    }
    else
    {
        <div class="alert alert-danger">
            <strong>Danger!</strong> There was an error in processing your request.
        </div>
    }
}*@
@*<div class="alert alert-danger">
    <strong>Message!</strong> @ViewBag.IsValid
</div>*@
<div class="jumbotron">
    <h1 class="display-4">XYZ Apartment Complex</h1>
    <p class="lead">This is a simple application, where tenants can register their vehicles and management can track vehicles park at the apartment complex.</p>
    <hr class="my-4" />
    <div>
        <p>Don't have an account?</p>
        <a href="@Url.Action("CreateAccount","Home")" class="btn-default">Create here</a>
    </div>
</div>
<div class="display">
    @*<div>
        <p>Please enter the following information in order to register a vehicle.</p>
        <form asp-controller="Home" asp-action="ValidateOwner"method="post">
        <div>
            <label asp-for="Owner.Email">Email</label>
            <input asp-for="Owner.Email" />
        </div>

        <div>
            <label asp-for="Owner.ApartmentNumber">Apartment Number</label>
            <input asp-for="Owner.ApartmentNumber" />
        </div>
        </form>
        
    </div>*@
            <div>
                <a asp-controller="vehicle" asp-action="Register" class="btn btn-primary"> Register your vehicle</a>
            </div>
    <div style="margin-left:30%;">
        <p>Search a vehicle by registration number.</p>
        <form asp-controller="Home" asp-action="FindVehicle" method="post">
            <div>
                <label asp-for="Vehicle.RegistrationNumber">Registration Number :</label>
                <input asp-for="Vehicle.RegistrationNumber" />
            </div>

            <div>
                <button type="submit">Search for Vehicle</button>
            </div>
        </form>

    </div>
</div>

DemoCoreApp/DemoCoreApp/Views/Home/OwnerVehicleInfo.cshtml
@model DemoCoreApp.ViewModels.OwnerVehicleViewModel
@{
    ViewData["Title"] = "Owner and Vehicle information";
}